// Create new user for guglielmo.farina@mail.com (Public. no Auth)
POST http://localhost:5000/api/v1/oauth2/register HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
  "from" : "data",
  "password" : "Passw0rd",
  "role": "user",
  "data": {
		"displayName" : "Guglielmo Farina",
		"photoURL": "assets/images/avatars/gfarina.jpg",
		"email" : "guglielmo.farina@gmail.com"
  }
}

###

// signInWithEmailAndPassword as guglielmo.farina@crowdservices.it
POST http://localhost:5000/api/v1/oauth2/sign-in HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
	"data": {
		"email" : "guglielmo.farina@crowdservices.it",
		"password" : "lpsddr$$4"	
	}
}

###

POST http://localhost:5000/api/v1/oauth2/sign-up HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
	"data": {
		"access_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk2YzZhNTBiZWE3MTIwZDc3Yjk4MiIsImF1ZCI6ImFkbWluIiwic3ViIjoiR3VnbGllbG1vIEZhcmluYSIsImlzcyI6IkNyb3dkIiwiaWF0IjoxNjYzMDAxNjE3LCJleHAiOjE2NjMwMDE5MTd9.lWj8T2LhHCq28LloJeP8QVLpGZlQDITdEcQgpa1e86Q"
	}
}

###

POST http://localhost:5000/api/v1/oauth2/access-token HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
	"data": {
		"access_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk2YzZhNTBiZWE3MTIwZDc3Yjk4MiIsImF1ZCI6ImFkbWluIiwic3ViIjoiR3VnbGllbG1vIEZhcmluYSIsImlzcyI6IkNyb3dkIiwiaWF0IjoxNjYzMDAxNjE3LCJleHAiOjE2NjMwMDE5MTd9.lWj8T2LhHCq28LloJeP8QVLpGZlQDITdEcQgpa1e86Q"
	}
}

###

// Refresh Toekn
POST http://localhost:5000/api/v1/oauth2/refresh-token HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
	"data": {
  		"refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk2YzZhNTBiZWE3MTIwZDc3Yjk4MiIsImF1ZCI6ImFkbWluIiwic3ViIjoiZ3VnbGllbG1vLmZhcmluYUBjcm93ZHNlcnZpY2VzLml0IiwiaXNzIjoiQ3Jvd2QiLCJpYXQiOjE2NjMxNzE1OTUsImV4cCI6MTY2MzE3MjE5NX0._cqE7zXLegdqhrPYGrzTuIt2JL8p0J5prh2q7x4f5TE"
	}
}

###

// Create new user for guglielmo.farina@mail.com (Public. no oauth2)
POST http://localhost:5000/api/v1/users HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
  "firstName" : "Guglielmo",
  "lastName" : "Farina",
  "email" : "guglielmo.farina@mail.com",
  "password" : "Passw0rd"
}

###

// Create new user for canon.europe@mail.com (Public. no oauth2)
POST http://localhost:5000/api/v1/users HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
  "firstName" : "Canon",
  "lastName" : "Europe",
  "email" : "canon.europe@mail.com",
  "password" : "Passw0rd"
}

###

// Generate JWT for user guglielmo.farina@gmail.com
POST http://localhost:5000/api/v1/oauth2 HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
  "email" : "guglielmo.farina@mail.com",
  "password" : "Passw0rd"
}

###

//Generate JWT for user canon.europe@mail.com
POST http://localhost:5000/api/v1/oauth2 HTTP/1.1
User-Agent: restbox
Content-Type: application/json

{
  "email" : "canon.europe@mail.com",
  "password" : "Passw0rd"
}

###

// Get User without Authorization
GET http://localhost:5000/api/v1/users/62696c6a50bea7120d77b982 HTTP/1.1
User-Agent: restbox
Content-Type: application/json

###

// Get User with Authorization
GET http://localhost:5000/api/v1/users/62696c6a50bea7120d77b982 HTTP/1.1
User-Agent: restbox
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjk2YzZhNTBiZWE3MTIwZDc3Yjk4MiIsImF1ZCI6ImFkbWluIiwic3ViIjoiR3VnbGllbG1vIEZhcmluYSIsImlzcyI6IkNyb3dkIiwiaWF0IjoxNjU4MTYzNjA0LCJleHAiOjE2NTgxNjM5MDR9.mK-ATDz7cL8IRhx3QtHU48Qd1lzy0Zl2rzNYY7E_5YQ

###

// Get User with fake Authorization
GET http://localhost:5000/api/v1/users/62696c6a50bea7120d77b982 HTTP/1.1
User-Agent: restbox
Content-Type: application/json
Authorization: Bearer xxxxxxxx.eyJ1c2VySWQiOiI2MDgwNWIyYmU3ZGIzMDQ1YWExOGFlYTAiLCJlbWFpbCI6Imd1Z2xpZWxtby5mYXJpbmFAbWFpbC5jb20iLCJwZXJtaXNzaW9uTGV2ZWwiOjIwNDgsInByb3ZpZGVyIjoiZW1haWwiLCJuYW1lIjoiR3VnbGllbG1vIEZhcmluYSIsInJlZnJlc2hLZXkiOiJ0NzRkNnJEc3ZIREx6cEsxWDJwZTFRPT0iLCJpYXQiOjE2NTAzNzQ0MDV9.mcZvCnJ6mioviWVhVElowXvS3G3TO6xhP1lUqTGk2Vw

###

// Get Users List without Authorization
GET http://localhost:5000/api/v1/users HTTP/1.1
User-Agent: restbox
Content-Type: application/json

###

// Get Users List with Authirization
GET http://localhost:5000/api/v1/users HTTP/1.1
User-Agent: restbox
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU0NzYwNzcxZDA0NjNmMWExOGFhNzMiLCJlbWFpbCI6ImNhbm9uLmV1cm9wZUBtYWlsLmNvbSIsInBlcm1pc3Npb25MZXZlbCI6NCwicHJvdmlkZXIiOiJlbWFpbCIsIm5hbWUiOiJDYW5vbiBFdXJvcGUiLCJyZWZyZXNoS2V5IjoiTFBISEJCWm0yaTgxWkhIS0VlS2JQZz09IiwiaWF0IjoxNjI1NjU3MDQ1fQ.KgXWIsjSwyznCl_WOAKaIF2zj4hxGKgvvTTe5kRXVPs

###

PATCH http://localhost:5000/users/6009776f857c3348f3e2a33f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU0NzYwNzcxZDA0NjNmMWExOGFhNzMiLCJlbWFpbCI6ImNhbm9uLmV1cm9wZUBtYWlsLmNvbSIsInBlcm1pc3Npb25MZXZlbCI6NCwicHJvdmlkZXIiOiJlbWFpbCIsIm5hbWUiOiJDYW5vbiBFdXJvcGUiLCJyZWZyZXNoS2V5IjoiTFBISEJCWm0yaTgxWkhIS0VlS2JQZz09IiwiaWF0IjoxNjI1NjU3MDQ1fQ.KgXWIsjSwyznCl_WOAKaIF2zj4hxGKgvvTTe5kRXVPs

{
  "firstName" : "John",
  "lastName" : "Snow"
}

###

DELETE http://localhost:5000/users/xxxotheruseridxxx HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDA5Nzc2Zjg1N2MzMzQ4ZjNlMmEzM2YiLCJlbWFpbCI6Im1hcmNvcy5zaWx2YUBtYWlsLmNvbSIsInBlcm1pc3Npb25MZXZlbCI6NSwicHJvdmlkZXIiOiJlbWFpbCIsIm5hbWUiOiJNYXJjb3MgU2lsdmEiLCJyZWZyZXNoS2V5IjoienZuZTJLaVFueWM5dkdBZUhJNENXZz09IiwiaWF0IjoxNjExMjQ0NTU5fQ.E7CgwuBSU8PCOe_l-yrn9SMFS7HkFgTE_vPFz3KBS34

###

GET http://localhost:5000/api/v1/sites HTTP/1.1
User-Agent: restbox
Content-Type: application/json

###

GET https://portaltest.crowdservices.it/api/v1/sites HTTP/1.1
User-Agent: restbox
Content-Type: application/json

###

GET http://localhost:5000/api/v1/sites/123 HTTP/1.1
User-Agent: restbox
Content-Type: application/json

###

// Soap Web Service
//POST https://portaltest.crowdservices.it/ws/v1/greatings?wsdl HTTP/1.1
POST https://portaltest.crowdservices.it/ws/v1/greatings HTTP/1.1
User-Agent: restbox
Content-Type: text/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:rec="http://test.web.smg.ms1.eu.gxs.com/gxs/ms/ws/provider/services/receiveWS">
    <soap:Header >
        <Security>
            <Username>username</Username>
            <Password>password</Password>
        </Security>
    </soap:Header>
    <soap:Body>
        <rec:GreatingsRequest xmlns="http://crowdservices.it/">
            <message>id1:12:34:56:out42</message>
            <splitter>:</splitter>
            <actionrequest>upload</actionrequest>
            <userid>IT_CROWD_TPM</userid>
            <password>password</password>
        </rec:GreatingsRequest>
    </soap:Body>
</soap:Envelope>

###

POST https://portaltest.crowdservices.it/ws/v1/upload HTTP/1.1
User-Agent: restbox
Content-Type: text/xml; charset=utf-8

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:rec="http://portal.crowdservices.it/receive">
   <soapenv:Header/>
   <soapenv:Body>
      <rec:receive>
         <rec:userid>IT_CROWD_TPM</rec:userid>
         <rec:password>password</rec:password>
         <inputData><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<_1:SyncActivityTPIMessage xmlns:_1="urn:one:canon:tpi:messages:activity:1" xmlns:_1_1="urn:one:canon:cdm:messages:common:1" xmlns:_1_10="urn:one:canon:cdm:bie:product:1" xmlns:_1_11="urn:one:canon:cdm:bie:part:1" xmlns:_1_12="urn:one:canon:cdm:bie:address:1" xmlns:_1_2="urn:one:canon:cdm:messages:activity:1" xmlns:_1_3="urn:one:canon:cdm:bie:servicerequest:1" xmlns:_1_4="urn:one:canon:cdm:bie:contact:1" xmlns:_1_5="urn:one:canon:cdm:bie:resource:1" xmlns:_1_6="urn:one:canon:cdm:bie:activity:1" xmlns:_1_7="urn:one:canon:cdm:types:1" xmlns:_1_8="urn:one:canon:cdm:bie:skill:1" xmlns:_1_9="urn:one:canon:cdm:bie:customerproduct:1">
	<SourceSystemName>Siebel</SourceSystemName>
	<SenderID>Canon</SenderID>
	<ReceiverID>IT_CROWD_TPM</ReceiverID>
	<Transaction>
		<Version>1.0</Version>
		<MessageType>Request</MessageType>
		<ServiceName>SyncActivity</ServiceName>
	</Transaction>
	<MessageID>5D63D7B1-013D-4000-E000-05ACAC18C70B</MessageID>
	<SyncActivityMessage action="CREATE">
		<_1_1:Header>
			<_1_1:EntityName>PushSyncActivity</_1_1:EntityName>
			<_1_1:SourceApplication>Siebel</_1_1:SourceApplication>
			<_1_1:IntegrationID>5D63D1BC-013D-4000-E000-05ACAC18C70B</_1_1:IntegrationID>
		</_1_1:Header>
		<_1_2:ServiceRequestList>
			<_1_2:ServiceRequestDetails>
				<_1_3:ServiceRequestID>1-344471156</_1_3:ServiceRequestID>
				<_1_3:ServiceRequestNumber>1-5P37N8</_1_3:ServiceRequestNumber>
				<_1_3:Type>Provide Support - Hardware</_1_3:Type>
				<_1_3:Summary>Escalated - Planning</_1_3:Summary>
				<_1_3:AccountName>XYZ</_1_3:AccountName>
				<_1_3:ContactDetails>
					<_1_4:FirstName>Devang</_1_4:FirstName>
					<_1_5:LastName>Mandli</_1_5:LastName>
					<_1_4:Communication>
						<_1_4:Email>devang.mandli@capgemini.com</_1_4:Email>
					</_1_4:Communication>
				</_1_3:ContactDetails>
				<_1_2:ActivityList>
					<_1_2:SyncActivityDetails>
						<_1_6:ActivityID>1-5P37OS</_1_6:ActivityID>
						<_1_6:Type>Resolution - Onsite</_1_6:Type>
						<_1_6:SubTypeCode>Engineer visit - SLA</_1_6:SubTypeCode>
						<_1_6:PriorityCode>3-Medium</_1_6:PriorityCode>
						<_1_2:PlannedDates>
							<_1_7:Start>2012-11-06T16:03:41.000Z</_1_7:Start>
							<_1_7:End>2012-11-08T16:03:41.000Z</_1_7:End>
						</_1_2:PlannedDates>
						<_1_6:AssigneeID>IT_CROWD_TPM</_1_6:AssigneeID>
						<_1_2:Status>Created</_1_2:Status>
						<_1_2:SubStatus>Dispatched</_1_2:SubStatus>
						<_1_2:Contact>
							<_1_4:FirstName>Devang</_1_4:FirstName>
							<_1_5:LastName>Mandli</_1_5:LastName>
							<_1_4:WorkPhone>
								<_1_7:DialNumber>+919900000000</_1_7:DialNumber>
							</_1_4:WorkPhone>
						</_1_2:Contact>
						<_1_2:EffortMeasure>60</_1_2:EffortMeasure>
						<_1_2:SkillSetList>
							<_1_8:SkillSet>
								<_1_8:Name>Competency</_1_8:Name>
								<_1_8:Skill>
									<_1_8:Skill>
										<_1_8:LowChar1>Hardware</_1_8:LowChar1>
										<_1_8:LowChar2>MUSTHAVE</_1_8:LowChar2>
										<_1_8:LowChar3>Allround</_1_8:LowChar3>
									</_1_8:Skill>
								</_1_8:Skill>
							</_1_8:SkillSet>
						</_1_2:SkillSetList>
						<_1_2:MeterReadList>
							<_1_9:Meter>
								<_1_9:Name>101 TOTAL</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>112 TOTAL BLACK LARGE</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>113 TOTAL BLACK SMALL</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>122 TOTAL COLOUR LARGE</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>123 TOTAL COLOUR SMALL</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>301 TOTAL PRINT</_1_9:Name>
							</_1_9:Meter>
						</_1_2:MeterReadList>
					</_1_2:SyncActivityDetails>
				</_1_2:ActivityList>
				<_1_2:CustomerProduct>
					<_1_2:CustomerProductDetails>
						<_1_10:DeviceID>1-1A8L-4484</_1_10:DeviceID>
						<_1_11:SerialID>JLY00527</_1_11:SerialID>
						<_1_11:DescriptionText>IR3100CN</_1_11:DescriptionText>
						<_1_10:ConnectivitySettings>
							<_1_10:Connectivity>false</_1_10:Connectivity>
						</_1_10:ConnectivitySettings>
						<_1_9:CustomerDescriptionText>IR3100CNGE Model</_1_9:CustomerDescriptionText>
						<_1_9:CustomerProductType>Hardware Device</_1_9:CustomerProductType>
						<_1_9:CustomerProductStatus>Installed Product</_1_9:CustomerProductStatus>
					</_1_2:CustomerProductDetails>
					<_1_2:CustomerProductLocation>
						<_1_9:Address>LONDON</_1_9:Address>
						<_1_9:City>FARIS RAWI</_1_9:City>
						<_1_9:Address2>XYZ,52 MOUNT STREET</_1_9:Address2>
						<_1_12:PostalCode>W1K 2SF</_1_12:PostalCode>
						<_1_12:Country>GB</_1_12:Country>
						<_1_9:Comment>52, MOUNT STREET</_1_9:Comment>
					</_1_2:CustomerProductLocation>
				</_1_2:CustomerProduct>
			</_1_2:ServiceRequestDetails>
		</_1_2:ServiceRequestList>
	</SyncActivityMessage>
</_1:SyncActivityTPIMessage>
]]></inputData>
      </rec:receive>
   </soapenv:Body>
</soapenv:Envelope>

###

POST http://104.155.12.14/PAT.CRM.WSC4/WSConnector.svc?singleWsdl HTTP/1.1
Content-Type: text/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" >
   <soapenv:Header />
   <soapenv:Body>
      <tem:ExecuteEx>
         <tem:xml>
            <Operations username="WS_HDA" password="HdAwS!InterNo@2022" parallelexecution="" >
               <Operation>
						<GetServerDateTime/>
               </Operation>
            </Operations>
         </tem:xml>
      </tem:ExecuteEx>
   </soapenv:Body>
</soapenv:Envelope>

###

//
POST http://localhost:5000/PAT.CRM.WSC4/WSConnector.svc HTTP/1.1
Content-Type: text/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" >
   <soap:Header />
   <soapenv:Body>
      <tem:ExecuteEx xmlns="http://tempuri.org/Imports" >
         <tem:xml>
            <Operations username="WS_HDA" password="HdAwS!InterNo@2022" parallelexecution="" >
               <Operation>
						<GetServerDateTime/>
               </Operation>
            </Operations>
         </tem:xml>
      </tem:ExecuteEx>
   </soapenv:Body>
</soapenv:Envelope>

###

POST http://localhost:5000/ws/v1/olivetti-inbound HTTP/1.1
User-Agent: restbox
Content-Type: text/xml; charset=utf-8

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:rec="http://portal.crowdservices.it/receive">
   <soapenv:Header/>
   <soapenv:Body>
      <rec:receive>
         <rec:userid>IT_CROWD_TPM</rec:userid>
         <rec:password>password</rec:password>
         <inputData><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<_1:SyncActivityTPIMessage xmlns:_1="urn:one:canon:tpi:messages:activity:1" xmlns:_1_1="urn:one:canon:cdm:messages:common:1" xmlns:_1_10="urn:one:canon:cdm:bie:product:1" xmlns:_1_11="urn:one:canon:cdm:bie:part:1" xmlns:_1_12="urn:one:canon:cdm:bie:address:1" xmlns:_1_2="urn:one:canon:cdm:messages:activity:1" xmlns:_1_3="urn:one:canon:cdm:bie:servicerequest:1" xmlns:_1_4="urn:one:canon:cdm:bie:contact:1" xmlns:_1_5="urn:one:canon:cdm:bie:resource:1" xmlns:_1_6="urn:one:canon:cdm:bie:activity:1" xmlns:_1_7="urn:one:canon:cdm:types:1" xmlns:_1_8="urn:one:canon:cdm:bie:skill:1" xmlns:_1_9="urn:one:canon:cdm:bie:customerproduct:1">
	<SourceSystemName>Siebel</SourceSystemName>
	<SenderID>Canon</SenderID>
	<ReceiverID>IT_CROWD_TPM</ReceiverID>
	<Transaction>
		<Version>1.0</Version>
		<MessageType>Request</MessageType>
		<ServiceName>SyncActivity</ServiceName>
	</Transaction>
	<MessageID>5D63D7B1-013D-4000-E000-05ACAC18C70B</MessageID>
	<SyncActivityMessage action="CREATE">
		<_1_1:Header>
			<_1_1:EntityName>PushSyncActivity</_1_1:EntityName>
			<_1_1:SourceApplication>Siebel</_1_1:SourceApplication>
			<_1_1:IntegrationID>5D63D1BC-013D-4000-E000-05ACAC18C70B</_1_1:IntegrationID>
		</_1_1:Header>
		<_1_2:ServiceRequestList>
			<_1_2:ServiceRequestDetails>
				<_1_3:ServiceRequestID>1-344471156</_1_3:ServiceRequestID>
				<_1_3:ServiceRequestNumber>1-5P37N8</_1_3:ServiceRequestNumber>
				<_1_3:Type>Provide Support - Hardware</_1_3:Type>
				<_1_3:Summary>Escalated - Planning</_1_3:Summary>
				<_1_3:AccountName>XYZ</_1_3:AccountName>
				<_1_3:ContactDetails>
					<_1_4:FirstName>Devang</_1_4:FirstName>
					<_1_5:LastName>Mandli</_1_5:LastName>
					<_1_4:Communication>
						<_1_4:Email>devang.mandli@capgemini.com</_1_4:Email>
					</_1_4:Communication>
				</_1_3:ContactDetails>
				<_1_2:ActivityList>
					<_1_2:SyncActivityDetails>
						<_1_6:ActivityID>1-5P37OS</_1_6:ActivityID>
						<_1_6:Type>Resolution - Onsite</_1_6:Type>
						<_1_6:SubTypeCode>Engineer visit - SLA</_1_6:SubTypeCode>
						<_1_6:PriorityCode>3-Medium</_1_6:PriorityCode>
						<_1_2:PlannedDates>
							<_1_7:Start>2012-11-06T16:03:41.000Z</_1_7:Start>
							<_1_7:End>2012-11-08T16:03:41.000Z</_1_7:End>
						</_1_2:PlannedDates>
						<_1_6:AssigneeID>IT_CROWD_TPM</_1_6:AssigneeID>
						<_1_2:Status>Created</_1_2:Status>
						<_1_2:SubStatus>Dispatched</_1_2:SubStatus>
						<_1_2:Contact>
							<_1_4:FirstName>Devang</_1_4:FirstName>
							<_1_5:LastName>Mandli</_1_5:LastName>
							<_1_4:WorkPhone>
								<_1_7:DialNumber>+919900000000</_1_7:DialNumber>
							</_1_4:WorkPhone>
						</_1_2:Contact>
						<_1_2:EffortMeasure>60</_1_2:EffortMeasure>
						<_1_2:SkillSetList>
							<_1_8:SkillSet>
								<_1_8:Name>Competency</_1_8:Name>
								<_1_8:Skill>
									<_1_8:Skill>
										<_1_8:LowChar1>Hardware</_1_8:LowChar1>
										<_1_8:LowChar2>MUSTHAVE</_1_8:LowChar2>
										<_1_8:LowChar3>Allround</_1_8:LowChar3>
									</_1_8:Skill>
								</_1_8:Skill>
							</_1_8:SkillSet>
						</_1_2:SkillSetList>
						<_1_2:MeterReadList>
							<_1_9:Meter>
								<_1_9:Name>101 TOTAL</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>112 TOTAL BLACK LARGE</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>113 TOTAL BLACK SMALL</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>122 TOTAL COLOUR LARGE</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>123 TOTAL COLOUR SMALL</_1_9:Name>
							</_1_9:Meter>
							<_1_9:Meter>
								<_1_9:Name>301 TOTAL PRINT</_1_9:Name>
							</_1_9:Meter>
						</_1_2:MeterReadList>
					</_1_2:SyncActivityDetails>
				</_1_2:ActivityList>
				<_1_2:CustomerProduct>
					<_1_2:CustomerProductDetails>
						<_1_10:DeviceID>1-1A8L-4484</_1_10:DeviceID>
						<_1_11:SerialID>JLY00527</_1_11:SerialID>
						<_1_11:DescriptionText>IR3100CN</_1_11:DescriptionText>
						<_1_10:ConnectivitySettings>
							<_1_10:Connectivity>false</_1_10:Connectivity>
						</_1_10:ConnectivitySettings>
						<_1_9:CustomerDescriptionText>IR3100CNGE Model</_1_9:CustomerDescriptionText>
						<_1_9:CustomerProductType>Hardware Device</_1_9:CustomerProductType>
						<_1_9:CustomerProductStatus>Installed Product</_1_9:CustomerProductStatus>
					</_1_2:CustomerProductDetails>
					<_1_2:CustomerProductLocation>
						<_1_9:Address>LONDON</_1_9:Address>
						<_1_9:City>FARIS RAWI</_1_9:City>
						<_1_9:Address2>XYZ,52 MOUNT STREET</_1_9:Address2>
						<_1_12:PostalCode>W1K 2SF</_1_12:PostalCode>
						<_1_12:Country>GB</_1_12:Country>
						<_1_9:Comment>52, MOUNT STREET</_1_9:Comment>
					</_1_2:CustomerProductLocation>
				</_1_2:CustomerProduct>
			</_1_2:ServiceRequestDetails>
		</_1_2:ServiceRequestList>
	</SyncActivityMessage>
</_1:SyncActivityTPIMessage>
]]></inputData>
      </rec:receive>
   </soapenv:Body>
</soapenv:Envelope>
